[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shield = "Hvz9QNiPfN3Q2oTnDCTTPun4k1TXJmRv3Vz7xCGRUaT6"

[programs.devnet]
shield = "Hvz9QNiPfN3Q2oTnDCTTPun4k1TXJmRv3Vz7xCGRUaT6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy/shield-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
