[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shield = "DuFBJmHcD2bhw1eE7xYYYramiQmCBzTLSRCi6tpWGTPF"

[programs.devnet]
shield = "DuFBJmHcD2bhw1eE7xYYYramiQmCBzTLSRCi6tpWGTPF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy/shield-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
